### ISSUE TITLE
Can't download dataset

### ISSUE THREAD

**Issue by harithapillai** [elliottwu/sText2Image#23]
Sir I can't download the CelebeA dataset by running the .sh file.
It shows that "wget: unable to resolve host address ‘celeba.tar.gz’" and "wget: unable to resolve host address ‘[www.robots.ox.ac.uk](http://www.robots.ox.ac.uk/)’
tar (child): celeba.tar.gz: Cannot open: No such file or directory".
Kindly help me to solve this.

**Comment by elliottwu** [comment]
should be fixed now.
